import { CADObject, MachineSettings, OperationItem } from '../types';

export const LOCAL_STORAGE_KEY = 'cnc_studio_project_v1';

export const INITIAL_MACHINE: MachineSettings = {
  units: 'mm',
  controllerProfile: 'ncstudio',
  bounds: {
    xMin: -1600,
    xMax: 0,
    yMin: -2000,
    yMax: 0,
  },
  stockSheet: {
    enabled: true,
    preset: '1000x1000',
    widthX: 1000,
    widthY: 1000,
    color: '#f59e0b',
  },
  workOffset: {
    x: 0,
    y: 0,
  },
  safeZ: 20,
  cutDepth: 5,
  spindleSpeed: 18000,
  spindleDwell: 3000,
  feedCut: 1200,
  feedPlunge: 300,
  feedDrill: 500,
  toolDiameter: 3.175,
  toolName: 'Фреза 3.175мм',
  useCannedCycles: true,
};

export const INITIAL_OBJECTS: CADObject[] = [
  {
    id: 'obj_hole_1',
    name: 'Отверстие 1 (X-100 Y-100)',
    type: 'point',
    x: -100,
    y: -100,
    diameter: 11.0,
    depth: 33,
    drillMode: '11mm',
    operationType: 'drill',
  },
  {
    id: 'obj_hole_2',
    name: 'Отверстие 2 (X-200 Y-100)',
    type: 'point',
    x: -200,
    y: -100,
    diameter: 9.0,
    depth: 33,
    drillMode: '9mm',
    operationType: 'drill',
  },
  {
    id: 'obj_line_1',
    name: 'Линия X 200мм',
    type: 'line',
    startX: -50,
    startY: -50,
    endX: -250,
    endY: -50,
    depth: 5,
    operationType: 'cut',
  },
  {
    id: 'obj_line_2',
    name: 'Линия Y 150мм',
    type: 'line',
    startX: -250,
    startY: -50,
    endX: -250,
    endY: -200,
    depth: 5,
    operationType: 'cut',
  },
];

export const INITIAL_OPERATIONS: OperationItem[] = [
  {
    id: 'op_drill_holes',
    name: 'Сверление отверстий',
    enabled: true,
    type: 'drill',
    linkedObjectIds: ['obj_hole_1', 'obj_hole_2'],
    safeZ: 5,
    startZ: 0,
    finalDepth: 33,
    passDepth: 16,
    spindleSpeed: 15000,
    feedCut: 1200,
    feedPlunge: 300,
    feedDrill: 1000,
    direction: 'cw',
    comment: 'Сверление отверстий 11мм и 9мм',
  },
  {
    id: 'op_cut_lines',
    name: 'Резка по линиям',
    enabled: true,
    type: 'cutContour',
    linkedObjectIds: ['obj_line_1', 'obj_line_2'],
    safeZ: 10,
    startZ: 0,
    finalDepth: 5,
    passDepth: 5,
    spindleSpeed: 15000,
    feedCut: 1200,
    feedPlunge: 300,
    feedDrill: 500,
    direction: 'cw',
    comment: 'Контурная резка по линиям',
  },
];
